# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.update_user_request_user import UpdateUserRequestUser

class TestUpdateUserRequestUser(unittest.TestCase):
    """UpdateUserRequestUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserRequestUser:
        """Test UpdateUserRequestUser
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserRequestUser`
        """
        model = UpdateUserRequestUser()
        if include_optional:
            return UpdateUserRequestUser(
                id = None,
                name = '',
                role = 'ROLE_UNSPECIFIED',
                email = '',
                full_name = '',
                show_tutorial = True,
                org_role = 'ACTOR_ROLE_UNSPECIFIED',
                private_info = ri.apiclient.models.user_private_info.userPrivateInfo(
                    favorite_projects = [
                        ri.apiclient.models.user_favorite_projects.userFavoriteProjects(
                            workspace_id = ri.apiclient.models.rime_uuid.rimeUUID(
                                uuid = '', ), 
                            project_ids = [
                                ri.apiclient.models.rime_uuid.rimeUUID(
                                    uuid = '', )
                                ], )
                        ], )
            )
        else:
            return UpdateUserRequestUser(
        )
        """

    def testUpdateUserRequestUser(self):
        """Test UpdateUserRequestUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()