# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.rime_get_datapoints_response import RimeGetDatapointsResponse

class TestRimeGetDatapointsResponse(unittest.TestCase):
    """RimeGetDatapointsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RimeGetDatapointsResponse:
        """Test RimeGetDatapointsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RimeGetDatapointsResponse`
        """
        model = RimeGetDatapointsResponse()
        if include_optional:
            return RimeGetDatapointsResponse(
                datapoints = [
                    ri.apiclient.models.datacollector_datapoint.datacollectorDatapoint(
                        datapoint_id = ri.apiclient.models.rime_uuid.rimeUUID(
                            uuid = '', ), 
                        data_stream_id = ri.apiclient.models.rime_uuid.rimeUUID(
                            uuid = '', ), 
                        datapoint = ri.apiclient.models.datapoint_row_contains_the_json_serialized_datapoint.DatapointRow contains the JSON serialized datapoint(
                            input_data = 'YQ==', 
                            label = 'YQ==', 
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            query_id = 'YQ==', ), )
                    ]
            )
        else:
            return RimeGetDatapointsResponse(
        )
        """

    def testRimeGetDatapointsResponse(self):
        """Test RimeGetDatapointsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()