# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.registry_hugging_face_model_info import RegistryHuggingFaceModelInfo

class TestRegistryHuggingFaceModelInfo(unittest.TestCase):
    """RegistryHuggingFaceModelInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegistryHuggingFaceModelInfo:
        """Test RegistryHuggingFaceModelInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegistryHuggingFaceModelInfo`
        """
        model = RegistryHuggingFaceModelInfo()
        if include_optional:
            return RegistryHuggingFaceModelInfo(
                model_uri = '',
                kwargs = ''
            )
        else:
            return RegistryHuggingFaceModelInfo(
                model_uri = '',
        )
        """

    def testRegistryHuggingFaceModelInfo(self):
        """Test RegistryHuggingFaceModelInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()