#kannada_keywords
kannada_keywords = {
    #Important Built-in Functions.
    'ಮುದ್ರಿಸು': 'print',
    'ವಿಧ': 'type',
    'ಒಳಸೇರಿಸು': 'input',
    'ಉದ್ದ': 'len',
    'ಸಾಲು': 'str',
    'ಪೂರ್ಣಸಂಖ್ಯೆ': 'int',
    'ಸಮ್ಮತ': 'float',
    'ಪಟ್ಟಿ': 'list',
    'ನೆರಕೆ': 'dict',
    'ರಾಶಿ': 'set',
    #Important Built-in Types.
    'ಟ್ಯೂಪಲ್ಸ್': 'tuple',
    'ಬೂಲ್': 'bool',
    #Important Control Flow Statements.
    'ಒಂದು_ವೇಳೆ': 'if',
    'ಇಲ್ಲದಿದ್ದರೆ': 'elif',
    'ಬೇರೆ': 'else',
    'ಬದಲು': 'for',
    'ವೇಳೆ': 'while',
    'ಮುರಿ': 'break',
    'ಮುಂದುವರೆಸು': 'continue',
    'ಹಿಂದಿರುಗು': 'return',
    'ಪ್ರಯತ್ನಿಸು': 'try',
    'ಹೊರತುಪಡಿಸಿ': 'except',
    'ಕೊನೆಯದಾಗಿ': 'finally',
    'ಜೊತೆಗೆ': 'with',
    #Additional words
    'ಕಾರ್ಯ': 'def',
    'ನಿಜ': 'True',
    'ಸುಳ್ಳು': 'False',
    'ತೇರ್ಗಡೆ': 'pass',
    'ವರ್ಗ': 'class',
    'ರಲ್ಲಿ': 'in',
    'ಲ್ಯಾಂಬ್ಡಾ': 'lambda',
    'ಹಳಿಸು': 'del',
    'ಸಮಗ್ರ': 'global',
}