# Generated by Django 4.0.7 on 2024-05-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_accounts', '0006_tradingaccount_bp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ENABLED'), (1, 'DISABLED'), (2, 'CLOSED')], default=0, verbose_name='Status'),
        ),
    ]
