# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.activity_description import ActivityDescription
from openapi_server import util


class ActivityDescriptionShow(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: ActivityDescription=None):
        """ActivityDescriptionShow - a model defined in OpenAPI

        :param data: The data of this ActivityDescriptionShow.
        """
        self.openapi_types = {
            'data': ActivityDescription
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ActivityDescriptionShow':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ActivityDescription_Show of this ActivityDescriptionShow.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ActivityDescriptionShow.


        :return: The data of this ActivityDescriptionShow.
        :rtype: ActivityDescription
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ActivityDescriptionShow.


        :param data: The data of this ActivityDescriptionShow.
        :type data: ActivityDescription
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
