# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.comment_create_request_data import CommentCreateRequestData
from openapi_server import util


class CommentCreateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: CommentCreateRequestData=None):
        """CommentCreateRequest - a model defined in OpenAPI

        :param data: The data of this CommentCreateRequest.
        """
        self.openapi_types = {
            'data': CommentCreateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CommentCreateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Comment_create_request of this CommentCreateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CommentCreateRequest.


        :return: The data of this CommentCreateRequest.
        :rtype: CommentCreateRequestData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CommentCreateRequest.


        :param data: The data of this CommentCreateRequest.
        :type data: CommentCreateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
