# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.contact_update_request_data import ContactUpdateRequestData
from openapi_server import util


class ContactUpdateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: ContactUpdateRequestData=None):
        """ContactUpdateRequest - a model defined in OpenAPI

        :param data: The data of this ContactUpdateRequest.
        """
        self.openapi_types = {
            'data': ContactUpdateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ContactUpdateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Contact_update_request of this ContactUpdateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ContactUpdateRequest.


        :return: The data of this ContactUpdateRequest.
        :rtype: ContactUpdateRequestData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ContactUpdateRequest.


        :param data: The data of this ContactUpdateRequest.
        :type data: ContactUpdateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
