# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.conversation import Conversation
from openapi_server import util


class ConversationList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: List[Conversation]=None):
        """ConversationList - a model defined in OpenAPI

        :param data: The data of this ConversationList.
        """
        self.openapi_types = {
            'data': List[Conversation]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ConversationList':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Conversation_List of this ConversationList.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ConversationList.

        Conversation List Response

        :return: The data of this ConversationList.
        :rtype: List[Conversation]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ConversationList.

        Conversation List Response

        :param data: The data of this ConversationList.
        :type data: List[Conversation]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
