# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.custom_action_create_request_data import CustomActionCreateRequestData
from openapi_server import util


class CustomActionCreateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: CustomActionCreateRequestData=None):
        """CustomActionCreateRequest - a model defined in OpenAPI

        :param data: The data of this CustomActionCreateRequest.
        """
        self.openapi_types = {
            'data': CustomActionCreateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CustomActionCreateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CustomAction_create_request of this CustomActionCreateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CustomActionCreateRequest.


        :return: The data of this CustomActionCreateRequest.
        :rtype: CustomActionCreateRequestData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CustomActionCreateRequest.


        :param data: The data of this CustomActionCreateRequest.
        :type data: CustomActionCreateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
