# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.grant_funding_source_create_request_data import GrantFundingSourceCreateRequestData
from openapi_server import util


class GrantFundingSourceCreateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: GrantFundingSourceCreateRequestData=None):
        """GrantFundingSourceCreateRequest - a model defined in OpenAPI

        :param data: The data of this GrantFundingSourceCreateRequest.
        """
        self.openapi_types = {
            'data': GrantFundingSourceCreateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GrantFundingSourceCreateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GrantFundingSource_create_request of this GrantFundingSourceCreateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GrantFundingSourceCreateRequest.


        :return: The data of this GrantFundingSourceCreateRequest.
        :rtype: GrantFundingSourceCreateRequestData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GrantFundingSourceCreateRequest.


        :param data: The data of this GrantFundingSourceCreateRequest.
        :type data: GrantFundingSourceCreateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
