# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.interest_charge import InterestCharge
from openapi_server import util


class InterestChargeList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: List[InterestCharge]=None):
        """InterestChargeList - a model defined in OpenAPI

        :param data: The data of this InterestChargeList.
        """
        self.openapi_types = {
            'data': List[InterestCharge]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'InterestChargeList':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The InterestCharge_List of this InterestChargeList.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this InterestChargeList.

        InterestCharge List Response

        :return: The data of this InterestChargeList.
        :rtype: List[InterestCharge]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InterestChargeList.

        InterestCharge List Response

        :param data: The data of this InterestChargeList.
        :type data: List[InterestCharge]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
