# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class LineItemUpdateRequestDataActivity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: int=None):
        """LineItemUpdateRequestDataActivity - a model defined in OpenAPI

        :param id: The id of this LineItemUpdateRequestDataActivity.
        """
        self.openapi_types = {
            'id': int
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'LineItemUpdateRequestDataActivity':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The LineItem_update_request_data_activity of this LineItemUpdateRequestDataActivity.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this LineItemUpdateRequestDataActivity.

        The unique identifier for a single Activity associated with the LineItem. The keyword `null` is not valid for this field.

        :return: The id of this LineItemUpdateRequestDataActivity.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LineItemUpdateRequestDataActivity.

        The unique identifier for a single Activity associated with the LineItem. The keyword `null` is not valid for this field.

        :param id: The id of this LineItemUpdateRequestDataActivity.
        :type id: int
        """

        self._id = id
