# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.matter_update_request_data import MatterUpdateRequestData
from openapi_server import util


class MatterUpdateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: MatterUpdateRequestData=None):
        """MatterUpdateRequest - a model defined in OpenAPI

        :param data: The data of this MatterUpdateRequest.
        """
        self.openapi_types = {
            'data': MatterUpdateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MatterUpdateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Matter_update_request of this MatterUpdateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this MatterUpdateRequest.


        :return: The data of this MatterUpdateRequest.
        :rtype: MatterUpdateRequestData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this MatterUpdateRequest.


        :param data: The data of this MatterUpdateRequest.
        :type data: MatterUpdateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
