# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amount: float=None, holder_id: int=None, mark_as_lien: bool=None):
        """MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner - a model defined in OpenAPI

        :param amount: The amount of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        :param holder_id: The holder_id of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        :param mark_as_lien: The mark_as_lien of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        """
        self.openapi_types = {
            'amount': float,
            'holder_id': int,
            'mark_as_lien': bool
        }

        self.attribute_map = {
            'amount': 'amount',
            'holder_id': 'holder_id',
            'mark_as_lien': 'mark_as_lien'
        }

        self._amount = amount
        self._holder_id = holder_id
        self._mark_as_lien = mark_as_lien

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The MedicalRecordsRequest_create_request_data_medical_bills_inner_payers_inner of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self):
        """Gets the amount of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.

        Lien amount.

        :return: The amount of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.

        Lien amount.

        :param amount: The amount of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        :type amount: float
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")

        self._amount = amount

    @property
    def holder_id(self):
        """Gets the holder_id of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.

        The unique identifier for a single Damage associated with the MedicalRecordsRequest. The keyword `null` is not valid for this field.

        :return: The holder_id of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        :rtype: int
        """
        return self._holder_id

    @holder_id.setter
    def holder_id(self, holder_id):
        """Sets the holder_id of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.

        The unique identifier for a single Damage associated with the MedicalRecordsRequest. The keyword `null` is not valid for this field.

        :param holder_id: The holder_id of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        :type holder_id: int
        """
        if holder_id is None:
            raise ValueError("Invalid value for `holder_id`, must not be `None`")

        self._holder_id = holder_id

    @property
    def mark_as_lien(self):
        """Gets the mark_as_lien of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.

        Mark record as Lien.

        :return: The mark_as_lien of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        :rtype: bool
        """
        return self._mark_as_lien

    @mark_as_lien.setter
    def mark_as_lien(self, mark_as_lien):
        """Sets the mark_as_lien of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.

        Mark record as Lien.

        :param mark_as_lien: The mark_as_lien of this MedicalRecordsRequestCreateRequestDataMedicalBillsInnerPayersInner.
        :type mark_as_lien: bool
        """
        if mark_as_lien is None:
            raise ValueError("Invalid value for `mark_as_lien`, must not be `None`")

        self._mark_as_lien = mark_as_lien
