# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.relationship import Relationship
from openapi_server import util


class RelationshipList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: List[Relationship]=None):
        """RelationshipList - a model defined in OpenAPI

        :param data: The data of this RelationshipList.
        """
        self.openapi_types = {
            'data': List[Relationship]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RelationshipList':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Relationship_List of this RelationshipList.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this RelationshipList.

        Relationship List Response

        :return: The data of this RelationshipList.
        :rtype: List[Relationship]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this RelationshipList.

        Relationship List Response

        :param data: The data of this RelationshipList.
        :type data: List[Relationship]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
