# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.task_template_create_request_data import TaskTemplateCreateRequestData
from openapi_server import util


class TaskTemplateCreateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: TaskTemplateCreateRequestData=None):
        """TaskTemplateCreateRequest - a model defined in OpenAPI

        :param data: The data of this TaskTemplateCreateRequest.
        """
        self.openapi_types = {
            'data': TaskTemplateCreateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TaskTemplateCreateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TaskTemplate_create_request of this TaskTemplateCreateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this TaskTemplateCreateRequest.


        :return: The data of this TaskTemplateCreateRequest.
        :rtype: TaskTemplateCreateRequestData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this TaskTemplateCreateRequest.


        :param data: The data of this TaskTemplateCreateRequest.
        :type data: TaskTemplateCreateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
