import Kratos
from typing import List

def CheckValidityOfModelPartsForOperations(main_model_part: Kratos.ModelPart, list_of_checking_model_parts: List[Kratos.ModelPart], thow_error: bool) -> bool: ...
def HasIntersection(model_parts_to_intersect: List[Kratos.ModelPart]) -> bool: ...
def Intersect(output_sub_model_part: Kratos.ModelPart, main_model_part: Kratos.ModelPart, model_parts_to_intersect: List[Kratos.ModelPart], add_neighbours: bool) -> None: ...
def Substract(output_sub_model_part: Kratos.ModelPart, main_model_part: Kratos.ModelPart, model_parts_to_substract: List[Kratos.ModelPart], add_neighbours: bool) -> None: ...
def Union(output_sub_model_part: Kratos.ModelPart, main_model_part: Kratos.ModelPart, model_parts_to_merge: List[Kratos.ModelPart], add_neighbours: bool) -> None: ...
