# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rbt/v1alpha1/tasks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18rbt/v1alpha1/tasks.proto\x12\x0crbt.v1alpha1\x1a\x19google/protobuf/any.proto\"B\n\x06TaskId\x12\x12\n\nstate_type\x18\x01 \x01(\t\x12\x11\n\tstate_ref\x18\x02 \x01(\t\x12\x11\n\ttask_uuid\x18\x03 \x01(\x0c\"4\n\x0bWaitRequest\x12%\n\x07task_id\x18\x01 \x01(\x0b\x32\x14.rbt.v1alpha1.TaskId\"{\n\x13TaskResponseOrError\x12(\n\x08response\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x12%\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x42\x13\n\x11response_or_error\"L\n\x0cWaitResponse\x12<\n\x11response_or_error\x18\x01 \x01(\x0b\x32!.rbt.v1alpha1.TaskResponseOrError\"O\n\x17ListPendingTasksRequest\x12\x1e\n\x11only_consensus_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x14\n\x12_only_consensus_id\"B\n\x18ListPendingTasksResponse\x12&\n\x08task_ids\x18\x01 \x03(\x0b\x32\x14.rbt.v1alpha1.TaskId\":\n\x11\x43\x61ncelTaskRequest\x12%\n\x07task_id\x18\x01 \x01(\x0b\x32\x14.rbt.v1alpha1.TaskId\"~\n\x12\x43\x61ncelTaskResponse\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.rbt.v1alpha1.CancelTaskResponse.Status\"/\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\r\n\tNOT_FOUND\x10\x01\x12\x0e\n\nCANCELLING\x10\x02\"\x14\n\x12TaskCancelledError2\xfa\x01\n\x05Tasks\x12=\n\x04Wait\x12\x19.rbt.v1alpha1.WaitRequest\x1a\x1a.rbt.v1alpha1.WaitResponse\x12\x61\n\x10ListPendingTasks\x12%.rbt.v1alpha1.ListPendingTasksRequest\x1a&.rbt.v1alpha1.ListPendingTasksResponse\x12O\n\nCancelTask\x12\x1f.rbt.v1alpha1.CancelTaskRequest\x1a .rbt.v1alpha1.CancelTaskResponseb\x06proto3')



_TASKID = DESCRIPTOR.message_types_by_name['TaskId']
_WAITREQUEST = DESCRIPTOR.message_types_by_name['WaitRequest']
_TASKRESPONSEORERROR = DESCRIPTOR.message_types_by_name['TaskResponseOrError']
_WAITRESPONSE = DESCRIPTOR.message_types_by_name['WaitResponse']
_LISTPENDINGTASKSREQUEST = DESCRIPTOR.message_types_by_name['ListPendingTasksRequest']
_LISTPENDINGTASKSRESPONSE = DESCRIPTOR.message_types_by_name['ListPendingTasksResponse']
_CANCELTASKREQUEST = DESCRIPTOR.message_types_by_name['CancelTaskRequest']
_CANCELTASKRESPONSE = DESCRIPTOR.message_types_by_name['CancelTaskResponse']
_TASKCANCELLEDERROR = DESCRIPTOR.message_types_by_name['TaskCancelledError']
_CANCELTASKRESPONSE_STATUS = _CANCELTASKRESPONSE.enum_types_by_name['Status']
TaskId = _reflection.GeneratedProtocolMessageType('TaskId', (_message.Message,), {
  'DESCRIPTOR' : _TASKID,
  '__module__' : 'rbt.v1alpha1.tasks_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.TaskId)
  })
_sym_db.RegisterMessage(TaskId)

WaitRequest = _reflection.GeneratedProtocolMessageType('WaitRequest', (_message.Message,), {
  'DESCRIPTOR' : _WAITREQUEST,
  '__module__' : 'rbt.v1alpha1.tasks_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.WaitRequest)
  })
_sym_db.RegisterMessage(WaitRequest)

TaskResponseOrError = _reflection.GeneratedProtocolMessageType('TaskResponseOrError', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESPONSEORERROR,
  '__module__' : 'rbt.v1alpha1.tasks_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.TaskResponseOrError)
  })
_sym_db.RegisterMessage(TaskResponseOrError)

WaitResponse = _reflection.GeneratedProtocolMessageType('WaitResponse', (_message.Message,), {
  'DESCRIPTOR' : _WAITRESPONSE,
  '__module__' : 'rbt.v1alpha1.tasks_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.WaitResponse)
  })
_sym_db.RegisterMessage(WaitResponse)

ListPendingTasksRequest = _reflection.GeneratedProtocolMessageType('ListPendingTasksRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTPENDINGTASKSREQUEST,
  '__module__' : 'rbt.v1alpha1.tasks_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.ListPendingTasksRequest)
  })
_sym_db.RegisterMessage(ListPendingTasksRequest)

ListPendingTasksResponse = _reflection.GeneratedProtocolMessageType('ListPendingTasksResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTPENDINGTASKSRESPONSE,
  '__module__' : 'rbt.v1alpha1.tasks_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.ListPendingTasksResponse)
  })
_sym_db.RegisterMessage(ListPendingTasksResponse)

CancelTaskRequest = _reflection.GeneratedProtocolMessageType('CancelTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _CANCELTASKREQUEST,
  '__module__' : 'rbt.v1alpha1.tasks_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.CancelTaskRequest)
  })
_sym_db.RegisterMessage(CancelTaskRequest)

CancelTaskResponse = _reflection.GeneratedProtocolMessageType('CancelTaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _CANCELTASKRESPONSE,
  '__module__' : 'rbt.v1alpha1.tasks_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.CancelTaskResponse)
  })
_sym_db.RegisterMessage(CancelTaskResponse)

TaskCancelledError = _reflection.GeneratedProtocolMessageType('TaskCancelledError', (_message.Message,), {
  'DESCRIPTOR' : _TASKCANCELLEDERROR,
  '__module__' : 'rbt.v1alpha1.tasks_pb2'
  # @@protoc_insertion_point(class_scope:rbt.v1alpha1.TaskCancelledError)
  })
_sym_db.RegisterMessage(TaskCancelledError)

_TASKS = DESCRIPTOR.services_by_name['Tasks']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKID._serialized_start=69
  _TASKID._serialized_end=135
  _WAITREQUEST._serialized_start=137
  _WAITREQUEST._serialized_end=189
  _TASKRESPONSEORERROR._serialized_start=191
  _TASKRESPONSEORERROR._serialized_end=314
  _WAITRESPONSE._serialized_start=316
  _WAITRESPONSE._serialized_end=392
  _LISTPENDINGTASKSREQUEST._serialized_start=394
  _LISTPENDINGTASKSREQUEST._serialized_end=473
  _LISTPENDINGTASKSRESPONSE._serialized_start=475
  _LISTPENDINGTASKSRESPONSE._serialized_end=541
  _CANCELTASKREQUEST._serialized_start=543
  _CANCELTASKREQUEST._serialized_end=601
  _CANCELTASKRESPONSE._serialized_start=603
  _CANCELTASKRESPONSE._serialized_end=729
  _CANCELTASKRESPONSE_STATUS._serialized_start=682
  _CANCELTASKRESPONSE_STATUS._serialized_end=729
  _TASKCANCELLEDERROR._serialized_start=731
  _TASKCANCELLEDERROR._serialized_end=751
  _TASKS._serialized_start=754
  _TASKS._serialized_end=1004
# @@protoc_insertion_point(module_scope)
