boutiques = [
    'The Fashion Hub', 'Electro World', 'Gadget Galaxy', 'Home Comforts', 'Style Street', 'Fitness First',
    'Toy Town', 'Book Nook', 'Beauty Bliss', 'Pet Paradise', 'Sporty Spot', 'Auto Arena', 'Crafty Corner',
    'Office Oasis', 'Outdoor Oasis', 'Health Haven', 'Gift Gallery', 'Kitchen Kingdom', 'Garden Grove',
    'Music Mart', 'Travel Treasures', 'Food Fiesta', 'Baby Bazaar', 'Trendy Threads', 'Tech Trends',
    'Cozy Corner', 'Chic Boutique', 'The Shoe Box', 'Jewelry Junction', 'Handbag Haven', 'Watch World',
    'Sunny Shades', 'Fitness Fanatics', 'Cycling Central', 'Yoga Yard', 'Team Titan', 'Car Corner',
    'Motorcycle Mania', 'Tool Town', 'Electronic Emporium', 'Book Barn', 'Kids\' Kingdom', 'Puzzle Palace',
    'Action Arena', 'Party Place', 'Wrap Wonders', 'Furniture Fortress', 'Bed & Beyond', 'Decor Delight',
    'Storage Solutions', 'Light Land', 'Garden Goods', 'Plant Palace', 'Guitar Garage', 'Keyboard Kingdom',
    'Drum Depot', 'Brass Boutique', 'Woodwind Warehouse', 'String Studio', 'DJ Den', 'Recording Room',
    'Luggage Land', 'Backpack Base', 'Gourmet Goodies', 'Snack Shack', 'Wine World', 'Coffee Corner',
    'Tea Time', 'Diaper Den', 'Feeding Frenzy', 'Baby Bliss', 'Nursery Nook', 'Safety Station', 'Men\'s Mode',
    'Women\'s Wardrobe', 'Kid\'s Closet', 'Men\'s Footwear', 'Women\'s Walk', 'Kid\'s Kicks', 'Accessories Avenue',
    'Exercise Essentials', 'Outdoor Outfitter', 'Cycling Craze', 'Running Realm', 'Health Hut', 'Beauty Box',
    'Tech Territory', 'Home Haven', 'Sport Supply', 'Pet Place', 'Craft Central', 'Office Outlet', 'Travel Totes',
    'Foodie Finds', 'Fitness Finds', 'Gadget Garage', 'Comfort Corner', 'Fashion Focus', 'Toy Treasure'
]


categories = [
    {"id": 1, "name": "Electronics", "parent": None},
    {"id": 2, "name": "Mobile Phones", "parent": 1},
    {"id": 3, "name": "Laptops", "parent": 1},
    {"id": 4, "name": "Smartphones", "parent": 2},
    {"id": 5, "name": "Feature Phones", "parent": 2},
    {"id": 6, "name": "Gaming Laptops", "parent": 3},
    {"id": 7, "name": "Tablets", "parent": 1},
    {"id": 8, "name": "Android Tablets", "parent": 7},
    {"id": 9, "name": "iOS Tablets", "parent": 7},
    {"id": 10, "name": "Televisions", "parent": 1},
    {"id": 11, "name": "LED TVs", "parent": 10},
    {"id": 12, "name": "Smart TVs", "parent": 10},
    {"id": 13, "name": "Cameras", "parent": 1},
    {"id": 14, "name": "DSLR Cameras", "parent": 13},
    {"id": 15, "name": "Mirrorless Cameras", "parent": 13},
    {"id": 16, "name": "Audio & Headphones", "parent": 1},
    {"id": 17, "name": "Headphones", "parent": 16},
    {"id": 18, "name": "Speakers", "parent": 16},
    {"id": 19, "name": "Wearable Technology", "parent": 1},
    {"id": 20, "name": "Smartwatches", "parent": 19},
    {"id": 21, "name": "Fitness Trackers", "parent": 19},
    {"id": 22, "name": "Gaming Consoles", "parent": 1},
    {"id": 23, "name": "PlayStation", "parent": 22},
    {"id": 24, "name": "Xbox", "parent": 22},
    {"id": 25, "name": "Computer Accessories", "parent": 1},
    {"id": 26, "name": "Keyboards", "parent": 25},
    {"id": 27, "name": "Mice", "parent": 25},
    {"id": 28, "name": "Printers & Scanners", "parent": 1},
    {"id": 29, "name": "Printers", "parent": 28},
    {"id": 30, "name": "Scanners", "parent": 28},
    {"id": 31, "name": "Smart Home Devices", "parent": 1},
    {"id": 32, "name": "Home Appliances", "parent": None},
    {"id": 33, "name": "Refrigerators", "parent": 32},
    {"id": 34, "name": "Washing Machines", "parent": 32},
    {"id": 35, "name": "Microwaves", "parent": 32},
    {"id": 36, "name": "Air Conditioners", "parent": 32},
    {"id": 37, "name": "Vacuum Cleaners", "parent": 32},
    {"id": 38, "name": "Small Kitchen Appliances", "parent": 32},
    {"id": 39, "name": "Health & Personal Care", "parent": None},
    {"id": 40, "name": "Beauty Products", "parent": 39},
    {"id": 41, "name": "Clothing", "parent": None},
    {"id": 42, "name": "Men's Clothing", "parent": 41},
    {"id": 43, "name": "Women's Clothing", "parent": 41},
    {"id": 44, "name": "Kid's Clothing", "parent": 41},
    {"id": 45, "name": "Footwear", "parent": None},
    {"id": 46, "name": "Men's Shoes", "parent": 45},
    {"id": 47, "name": "Women's Shoes", "parent": 45},
    {"id": 48, "name": "Kid's Shoes", "parent": 45},
    {"id": 49, "name": "Jewelry & Accessories", "parent": None},
    {"id": 50, "name": "Watches", "parent": 49},
    {"id": 51, "name": "Handbags", "parent": 49},
    {"id": 52, "name": "Sunglasses", "parent": 49},
    {"id": 53, "name": "Sports & Fitness", "parent": None},
    {"id": 54, "name": "Exercise Equipment", "parent": 53},
    {"id": 55, "name": "Outdoor Gear", "parent": 53},
    {"id": 56, "name": "Cycling", "parent": 53},
    {"id": 57, "name": "Running", "parent": 53},
    {"id": 58, "name": "Yoga", "parent": 53},
    {"id": 59, "name": "Team Sports", "parent": 53},
    {"id": 60, "name": "Sportswear", "parent": 53},
    {"id": 61, "name": "Nutrition & Supplements", "parent": 53},
    {"id": 62, "name": "Automotive", "parent": None},
    {"id": 63, "name": "Car Accessories", "parent": 62},
    {"id": 64, "name": "Motorcycle Accessories", "parent": 62},
    {"id": 65, "name": "Tools & Equipment", "parent": 62},
    {"id": 66, "name": "Car Electronics", "parent": 62},
    {"id": 67, "name": "Books", "parent": None},
    {"id": 68, "name": "Fiction", "parent": 67},
    {"id": 69, "name": "Non-Fiction", "parent": 67},
    {"id": 70, "name": "Children's Books", "parent": 67},
    {"id": 71, "name": "Educational Books", "parent": 67},
    {"id": 72, "name": "E-books", "parent": 67},
    {"id": 73, "name": "Stationery", "parent": None},
    {"id": 74, "name": "Office Supplies", "parent": 73},
    {"id": 75, "name": "Art Supplies", "parent": 73},
    {"id": 76, "name": "Toys & Games", "parent": None},
    {"id": 77, "name": "Action Figures", "parent": 76},
    {"id": 78, "name": "Dolls & Accessories", "parent": 76},
    {"id": 79, "name": "Puzzles", "parent": 76},
    {"id": 80, "name": "Board Games", "parent": 76},
    {"id": 81, "name": "Outdoor Toys", "parent": 76},
    {"id": 82, "name": "Video Games", "parent": 76},
    {"id": 83, "name": "Pet Supplies", "parent": None},
    {"id": 84, "name": "Dog Supplies", "parent": 83},
    {"id": 85, "name": "Cat Supplies", "parent": 83},
    {"id": 86, "name": "Fish Supplies", "parent": 83},
    {"id": 87, "name": "Bird Supplies", "parent": 83},
    {"id": 88, "name": "Reptile Supplies", "parent": 83},
    {"id": 89, "name": "Crafts & Sewing", "parent": None},
    {"id": 90, "name": "Fabric", "parent": 89},
    {"id": 91, "name": "Sewing Supplies", "parent": 89},
    {"id": 92, "name": "Knitting & Crochet", "parent": 89},
    {"id": 93, "name": "Party Supplies", "parent": None},
    {"id": 94, "name": "Gift Wrap", "parent": 93},
    {"id": 95, "name": "Home & Garden", "parent": None},
    {"id": 96, "name": "Furniture", "parent": 95},
    {"id": 97, "name": "Bedding", "parent": 95},
    {"id": 98, "name": "Home Decor", "parent": 95},
    {"id": 99, "name": "Kitchen & Dining", "parent": 95},
    {"id": 100, "name": "Storage & Organization", "parent": 95},
    {"id": 101, "name": "Lighting", "parent": 95},
    {"id": 102, "name": "Outdoor Furniture", "parent": 95},
    {"id": 103, "name": "Garden Tools", "parent": 95},
    {"id": 104, "name": "Lawn Care", "parent": 95},
    {"id": 105, "name": "Plants & Seeds", "parent": 95},
    {"id": 106, "name": "Musical Instruments", "parent": None},
    {"id": 107, "name": "Guitars", "parent": 106},
    {"id": 108, "name": "Keyboards", "parent": 106},
    {"id": 109, "name": "Drums & Percussion", "parent": 106},
    {"id": 110, "name": "Brass Instruments", "parent": 106},
    {"id": 111, "name": "Woodwind Instruments", "parent": 106},
    {"id": 112, "name": "String Instruments", "parent": 106},
    {"id": 113, "name": "DJ Equipment", "parent": 106},
    {"id": 114, "name": "Recording Equipment", "parent": 106},
    {"id": 115, "name": "Travel & Luggage", "parent": None},
    {"id": 116, "name": "Luggage", "parent": 115},
    {"id": 117, "name": "Backpacks", "parent": 115},
    {"id": 118, "name": "Travel Accessories", "parent": 115},
    {"id": 119, "name": "Food & Beverages", "parent": None},
    {"id": 120, "name": "Gourmet Food", "parent": 119},
    {"id": 121, "name": "Snacks", "parent": 119},
    {"id": 122, "name": "Beverages", "parent": 119},
    {"id": 123, "name": "Wine & Spirits", "parent": 119},
    {"id": 124, "name": "Coffee & Tea", "parent": 119},
    {"id": 125, "name": "Baby Products", "parent": None},
    {"id": 126, "name": "Diapers", "parent": 125},
    {"id": 127, "name": "Feeding", "parent": 125},
    {"id": 128, "name": "Baby Gear", "parent": 125},
    {"id": 129, "name": "Nursery Furniture", "parent": 125},
    {"id": 130, "name": "Safety Equipment", "parent": 125}
]



def get_category_name_by_id(category_id, categories):
    """
    Function to get the category name by its ID.
    
    :param category_id: ID of the category to look up
    :param categories: List of category dictionaries
    :return: Name of the category if found, else None
    """
    for category in categories:
        if category['id'] == category_id:
            return category['name']
    return None