# coding: utf-8

# flake8: noqa
"""
    Schemantis API

    This the documentation for the Schemantis REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from schemantis.models.retrieve_map_post_request import RetrieveMapPostRequest
from schemantis.models.retrieve_map_post_request_config import (
    RetrieveMapPostRequestConfig,
)
