cell_enums = [
    {
        "tab": "Dataset Resource",
        "cell_name": "dataset theme (from data.gov.uk - included for illustrative purposes only until an agreed set is given to us)",
        "possible_values": [
            "Business and economy",
            "Crime and justice",
            "Defence",
            "Education",
            "Environment",
            "Government",
            "Government spending",
            "Health",
            "Mapping",
            "Society",
            "Towns and cities",
            "Transport",
            "Digital service performance",
            "Government reference data",
        ],
    },
    {
        "tab": "Dataset Resource",
        "cell_name": "Legal Gateway",
        "possible_values": [
            "Digital Economy Act 2017",
            "Statistics and Registration Service Act 2007",
            "NHS Act 2006",
            "NHS Act 2006 with COPI Regulations 2002, Reg 3(4)",
            "Health and Social Care Act 2012",
            "Education Act 1996 / 2011",
            "Education and Skills Act 2008",
            "Children's Act 1989",
            "Legal Gateway Not Required",
            "Other",
        ],
    },
    {
        "tab": "Dataset Resource",
        "cell_name": "Licensing Status",
        "possible_values": [
            "Open Data Commons Open Database License (ODbL)",
            "Open Government Licence v3.0",
            "Open Government Licence v2.0",
            "Open Government Licence v1.0",
            "Statistics and Registration Service Act 2007",
            "Non-Commercial Government Licence v2.0",
            "Non-Commercial Government Licence v1.0",
            "Developer Licence 2.0",
            "Developer Licence 1.0",
            "Charged Licence",
            "Open Supreme Court Licence",
            "Restricted",
            "Memorandum of Understanding (MoU)",
        ],
    },
    {
        "tab": "Dataset Resource",
        "cell_name": "Dataset Resource Type",
        "possible_values": [
            "Dataset Series",
            "Longitudinal",
            "Survey",
            "Statistical Output - Experimental",
            "Statistical Output - Key",
            "Statistical Output - National",
            "Reference",
            "Code List",
            "Administrative",
        ],
    },
    {
        "tab": "Resource AND Series",
        "cell_name": "Frequency (periodicity)",
        "possible_values": [
            "Annual",
            "Biennial",
            "Bimonthly",
            "Biweekly",
            "Continuous",
            "Daily",
            "Historical",
            "Irregular",
            "Monthly",
            "Periodic",
            "Quarterly",
            "Real Time",
            "Semiannual",
            "Semimonthly",
            "Semiweekly",
            "Single",
            "Three times a month",
            "Three times a week",
            "Three times a year",
            "Triennial",
            "Weekly",
        ],
    },
    {
        "tab": "Dataset Series",
        "cell_name": "Supply Type",
        "possible_values": ["Full ", "Append"],
    },
    {
        "tab": "Series AND Back Office",
        "cell_name": "Security Classification",
        "possible_values": [
            "Official",
            "Official-Sensitive",
            "Secret",
            "Top Secret",
            "Non-Applicable",
        ],
    },
    {
        "tab": "Dataset File",
        "cell_name": "File Format",
        "possible_values": ["CSV", "JSON", "PARQUET", "JSON Multi-Line"],
    },
    {
        "tab": "Dataset File",
        "cell_name": "Column Separator",
        "possible_values": [",", "|", "\\t"],
    },
    {
        "tab": "Dataset File",
        "cell_name": "Is file a sequence",
        "possible_values": ["Yes", "No"],
    },
    {"tab": "Variables", "cell_name": "PII", "possible_values": ["Yes", "No"]},
    {
        "tab": "Variables",
        "cell_name": "variable datatypes",
        "possible_values": [
            "ARRAY",
            "BIGINT",
            "BINARY",
            "BINARYDOUBLE",
            "BINARYFLOAT",
            "BIT",
            "BOOLEAN",
            "CHAR",
            "CURRENCY",
            "DATE",
            "DATETIME",
            "DECIMAL",
            "DOUBLE",
            "FLOAT",
            "INT",
            "INTEGER",
            "LONG",
            "LONGTEXT",
            "OBJECT",
            "NUMBER",
            "NUMERIC",
            "OBJECTID",
            "SHORTTEXT",
            "SMALLINT",
            "STRING",
            "TEXT",
            "TIME",
            "TIMESTAMP",
            "TINYINT",
            "VARCHAR",
            "REAL",
            "ARCHAR2",
            "CLOB",
            "LONG",
            "OBJECT",
            "ZERO-TERMINATEDBYTES",
            "UNICODESTRING",
            "INT32",
            "INT8",
            "INT16",
            "NVARCHAR",
            "NCHAR",
            "NTEXT",
            "NUMERICAL",
            "FLOATING POINT",
            "Pandas - DATETIME",
            "Pandas - STRING",
            "Pandas - DOUBLE",
        ],
    },
    {
        "tab": "Variables",
        "cell_name": "BigQuery datatypes",
        "possible_values": [
            "ARRAY",
            "BIGNUMBER",
            "STRING",
            "FLOAT64",
            "FLOAT64",
            "BOOL",
            "BOOL",
            "STRING",
            "INT64",
            "DATE",
            "TIMESTAMP",
            "FLOAT64",
            "FLOAT64",
            "FLOAT64",
            "INT64",
            "INT64",
            "INT64",
            "STRING",
            "INTERVAL",
            "INT64",
            "INT64",
            "STRING",
            "STRING",
            "INT64",
            "STRING",
            "STRING",
            "TIME",
            "TIMESTAMP",
            "INT64",
            "STRING",
            "FLOAT64",
            "STRING",
            "STRING",
            "STRING",
            "STRING",
            "STRING",
            "STRING",
            "INT64",
            "INT64",
            "INT64",
            "STRING",
            "STRING",
            "STRING",
            "INT64",
            "FLOAT64",
            "TIMESTAMP",
            "STRING",
            "FLOAT64",
        ],
    },
    {
        "tab": "Variables",
        "cell_name": "Is Primary Key",
        "possible_values": ["Yes", "No"],
    },
    {
        "tab": "Variables",
        "cell_name": "Is Foreign Key",
        "possible_values": ["Yes", "No"],
    },
    {
        "tab": "Variables",
        "cell_name": "Nullability",
        "possible_values": ["NOT NULL"],
    },
    {
        "tab": "Variables",
        "cell_name": "Is this a code?",
        "possible_values": ["Yes", "No"],
    },
    {
        "tab": "Back Office",
        "cell_name": "Dataset Domain",
        "possible_values": [
            "Crime and Justice",
            "Economics",
            "Government finance, Fiscal and Public Sector finances",
            "Human settlements and housing",
            "Income and Consumption",
            "Education ",
            "Health ",
            "Labour",
            "Population and Migration",
        ],
    },
    {
        "tab": "Back Office",
        "cell_name": "Metadata Access",
        "possible_values": [
            "Publish to Website & Hub",
            "Publish to Hub only",
            "Do not publish",
        ],
    },
    {
        "tab": "Back Office",
        "cell_name": "Should this dataset be visible for internal or external users?",
        "possible_values": ["Internal only", "Internal and External"],
    },
    {
        "tab": "Back Office",
        "cell_name": "sensitivity level",
        "possible_values": ["Low", "Medium", "High"],
    },
    {
        "tab": "Back Office",
        "cell_name": "Restrictions for Access",
        "possible_values": [
            "Access for all accredited researchers",
            "Access limited to specific researchers",
            "Limited to specific individuals",
        ],
    },
    {
        "tab": "Back Office",
        "cell_name": "Research Outputs",
        "possible_values": [
            "Research outputs must be sent to the data owner",
            "Research outputs must be approved by the data owner",
            "No requirements",
        ],
    },
    {
        "tab": "Back Office",
        "cell_name": "Research Disclaimer",
        "possible_values": [
            "A disclaimer must be published with research outputs",
            "No requirements",
        ],
    },
    {
        "tab": "Back Office",
        "cell_name": "Disclosure Control",
        "possible_values": [
            "Standard disclosure rules apply",
            "Bespoke disclosure rules apply",
        ],
    },
    {
        "tab": "Back Office",
        "cell_name": "Project Approval",
        "possible_values": [
            "Projects must be accredited and have approval from the data owner",
            "Projects must be accredited",
        ],
    },
]
