#
ROLE_CONFIGS = {
    "cmar": [
        ("Dataset Resource", "Dataset Resource Name"),
        # ("Dataset Resource", "Acronym"),
        # ("Dataset Resource", "Significant Changes"),
        ("Dataset Resource", "Data Creator"),
        # ("Dataset Resource", "Data Contributor(s)"),
        ("Dataset Resource", "Purpose of this Dataset Resource"),
        ("Dataset Resource", "Search keywords"),
        ("Dataset Resource", "Dataset Theme"),
        # ("Dataset Resource", "Geographic Level"),
        # ("Dataset Resource", "Provenance"),
        ("Dataset Resource", "Number of Dataset Series"),
        ("Dataset Resource", "Number of structural data files"),
        ("Dataset Resource", "Date of completion"),
        (
            "Dataset Resource",
            "Name and email of individual completing this template",
        ),
        ("Dataset Resource", "Security Classification"),
        ("Dataset Resource", "Dataset Resource type"),
        ("Dataset Resource", "Number of non-structural/reference files "),
        ("Dataset Resource", "Number of code list files"),
        ("Dataset Series", "Dataset Series Name"),
        ("Dataset Series", "Google Cloud Platform BigQuery Table Name"),
        ("Dataset Series", "Description"),
        ("Dataset Series", "Reference Period"),
        ("Dataset Series", "Geographic Coverage"),
        ("Dataset Series", "Frequency"),
        ("Dataset Series", "Supply Type"),
        # ("Dataset Series", "Wave number/time period covered (Survey only)"),
        # ("Dataset Series", "Links to online documentation and other useful materials"),
        ("Dataset File", "Google Cloud Platform BigQuery Table Name"),
        ("Dataset File", "File path and name"),
        ("Dataset File", "File Format"),
        # ("Dataset File", "Column Seperator"),
        # ("Dataset File", "String identifier"),
        ("Dataset File", "File description"),
        ("Dataset File", "Reference period"),
        ("Dataset File", "File size"),
        ("Dataset File", "File size unit"),
        ("Dataset File", "Is code list"),
        ("Dataset File", "Number of records"),
        (
            "Dataset File",
            "Is this file one of a sequence to be appended back together?",
        ),
        ("Dataset File", "Number of header rows"),
        ("Dataset File", "Number of footer rows"),
        # ("Dataset File", "Character encoding"),
        # ("Dataset File", "Hash value for checksum"),
        # ("Dataset File", "Notes"),
        ("Variables", "Google Cloud Platform BigQuery Table Name"),
        ("Variables", "Variable name"),
        ("Variables", "Google Cloud Platform compatible variable name"),
        ("Variables", "Variable label"),
        ("Variables", "Variable description"),
        ("Variables", "Position in file"),
        ("Variables", "Personally Identifiable Information"),
        ("Variables", "Variable Data Type"),
        # ("Variables", "GCP Data Type"),
        # ("Variables", "Variable length/precision"),
        # ("Variables", "Variable format"),
        ("Variables", "Is Primary Key"),
        ("Variables", "Is Foreign Key"),
        # ("Variables", "Foreign Key file name"),
        # ("Variables", "Foreign Key variable name"),
        ("Variables", "Nullability"),
        # ("Variables", "Null values denoted by"),
        # ("Variables", "Variable constraints"),
        # ("Variables", "Applicable business rules"),
        ("Variables", "Is this a code?"),
        # ("Variables", "Notes"),
        ("Codes and Values", "Google Cloud Platform BigQuery Table Name"),
        ("Codes and Values", "Variable name"),
        ("Codes and Values", "Key"),
        ("Codes and Values", "Value"),
        ("Codes and Values", "Notes"),
        ("Back Office", "IDS Business Catalogue Identifier"),
        ("Back Office", "Description"),
        ("Back Office", "Abstract"),
        ("Back Office", "Google Cloud Platform Project name"),
        ("Back Office", "Google Cloud Platform Big Query Dataset name"),
        # ("Back Office", "Other Unique Identifier(s) for Dataset Resource"),
        ("Back Office", "Frequency "),
        ("Back Office", "Geographic Coverage"),
        ("Back Office", "Temporal Coverage"),
        ("Back Office", "Sensitivity status for Dataset Resource"),
        ("Back Office", "Sensitivity tool URL"),
        ("Back Office", "Retention Date"),
        # ("Back Office", "Provider statement for retention, removal or deletion"),
        # ("Back Office", "Removal Date"),
        ("Back Office", "Removal Comments"),
        ("Back Office", "Data Controller"),
        # ("Back Office", "Data Processor"),
        ("Back Office", "Dataset Domain"),
        # ("Back Office", "Legal Gateway"),
        # ("Back Office", "Other Legal Gateway"),
        # ("Back Office", "Licensing status"),
        ("Back Office", "Metadata Access"),
        ("Back Office", "Documentation"),
        (
            "Back Office",
            "What are the linkage requirements for the data within the project scope?",
        ),
        ("Back Office", "How has deidentification been achieved?"),
        (
            "Back Office",
            "Should this dataset be visible for internal or external users?",
        ),
        ("Back Office", "Restrictions for Access"),
        ("Back Office", "Research Outputs"),
        ("Back Office", "Project Approval"),
        ("Back Office", "Disclosure Control"),
        ("Back Office", "Research Disclaimer"),
    ],
    "full": [
        ("Dataset Resource", "Dataset Resource Name"),
        ("Dataset Resource", "Acronym"),
        ("Dataset Resource", "Significant Changes"),
        ("Dataset Resource", "Data Creator"),
        ("Dataset Resource", "Data Contributor(s)"),
        ("Dataset Resource", "Purpose of this Dataset Resource"),
        ("Dataset Resource", "Search keywords"),
        ("Dataset Resource", "Dataset Theme"),
        ("Dataset Resource", "Geographic Level"),
        ("Dataset Resource", "Provenance"),
        ("Dataset Resource", "Number of Dataset Series"),
        ("Dataset Resource", "Number of structural data files"),
        ("Dataset Resource", "Date of completion"),
        (
            "Dataset Resource",
            "Name and email of individual completing this template",
        ),
        ("Dataset Resource", "Security Classification"),
        ("Dataset Resource", "Dataset Resource type"),
        ("Dataset Resource", "Number of non-structural/reference files "),
        ("Dataset Resource", "Number of code list files"),
        ("Dataset Series", "Dataset Series Name"),
        ("Dataset Series", "Google Cloud Platform BigQuery Table Name"),
        ("Dataset Series", "Description"),
        ("Dataset Series", "Reference Period"),
        ("Dataset Series", "Geographic Coverage"),
        ("Dataset Series", "Frequency"),
        ("Dataset Series", "Supply Type"),
        ("Dataset Series", "Wave number/time period covered (Survey only)"),
        (
            "Dataset Series",
            "Links to online documentation and other useful materials",
        ),
        ("Dataset File", "Google Cloud Platform BigQuery Table Name"),
        ("Dataset File", "File path and name"),
        ("Dataset File", "File Format"),
        ("Dataset File", "Column Seperator"),
        ("Dataset File", "String identifier"),
        ("Dataset File", "File description"),
        ("Dataset File", "Reference period"),
        ("Dataset File", "File size"),
        ("Dataset File", "File size unit"),
        ("Dataset File", "Is code list"),
        ("Dataset File", "Number of records"),
        (
            "Dataset File",
            "Is this file one of a sequence to be appended back together?",
        ),
        ("Dataset File", "Number of header rows"),
        ("Dataset File", "Number of footer rows"),
        ("Dataset File", "Character encoding"),
        ("Dataset File", "Hash value for checksum"),
        ("Dataset File", "Notes"),
        ("Variables", "Google Cloud Platform BigQuery Table Name"),
        ("Variables", "Variable name"),
        ("Variables", "Google Cloud Platform compatible variable name"),
        ("Variables", "Variable label"),
        ("Variables", "Variable description"),
        ("Variables", "Position in file"),
        ("Variables", "Personally Identifiable Information"),
        ("Variables", "Variable Data Type"),
        ("Variables", "GCP Data Type"),
        ("Variables", "Variable length/precision"),
        ("Variables", "Variable format"),
        ("Variables", "Is Primary Key"),
        ("Variables", "Is Foreign Key"),
        ("Variables", "Foreign Key file name"),
        ("Variables", "Foreign Key variable name"),
        ("Variables", "Nullability"),
        ("Variables", "Null values denoted by"),
        ("Variables", "Variable constraints"),
        ("Variables", "Applicable business rules"),
        ("Variables", "Is this a code?"),
        ("Variables", "Notes"),
        ("Codes and Values", "Google Cloud Platform BigQuery Table Name"),
        ("Codes and Values", "Variable name"),
        ("Codes and Values", "Key"),
        ("Codes and Values", "Value"),
        ("Codes and Values", "Notes"),
        ("Back Office", "IDS Business Catalogue Identifier"),
        ("Back Office", "Description"),
        ("Back Office", "Abstract"),
        ("Back Office", "Google Cloud Platform Project name"),
        ("Back Office", "Google Cloud Platform Big Query Dataset name"),
        ("Back Office", "Other Unique Identifier(s) for Dataset Resource"),
        ("Back Office", "Frequency "),
        ("Back Office", "Geographic Coverage"),
        ("Back Office", "Temporal Coverage"),
        ("Back Office", "Sensitivity status for Dataset Resource"),
        ("Back Office", "Sensitivity tool URL"),
        ("Back Office", "Retention Date"),
        (
            "Back Office",
            "Provider statement for retention, removal or deletion",
        ),
        ("Back Office", "Removal Date"),
        ("Back Office", "Removal Comments"),
        ("Back Office", "Data Controller"),
        ("Back Office", "Data Processor"),
        ("Back Office", "Dataset Domain"),
        ("Back Office", "Legal Gateway"),
        ("Back Office", "Other Legal Gateway"),
        ("Back Office", "Licensing status"),
        ("Back Office", "Metadata Access"),
        ("Back Office", "Documentation"),
        (
            "Back Office",
            "What are the linkage requirements for the data within the project scope?",
        ),
        ("Back Office", "How has deidentification been achieved?"),
        (
            "Back Office",
            "Should this dataset be visible for internal or external users?",
        ),
        ("Back Office", "Restrictions for Access"),
        ("Back Office", "Research Outputs"),
        ("Back Office", "Project Approval"),
        ("Back Office", "Disclosure Control"),
        ("Back Office", "Research Disclaimer"),
    ],
    "extract": [
        # ("Dataset Resource", "Number of Dataset Series"),
        # ("Dataset Resource", "Number of structural data files"),
        ("Dataset Series", "Dataset Series Name"),
        ("Dataset Series", "Google Cloud Platform BigQuery Table Name"),
        ("Dataset Series", "Supply Type"),
        ("Dataset File", "Google Cloud Platform BigQuery Table Name"),
        ("Dataset File", "File path and name"),
        ("Dataset File", "File Format"),
        ("Dataset File", "Column Seperator"),
        ("Dataset File", "File size"),
        ("Dataset File", "File size unit"),
        ("Dataset File", "Number of records"),
        (
            "Dataset File",
            "Is this file one of a sequence to be appended back together?",
        ),
        ("Dataset File", "Number of header rows"),
        ("Dataset File", "Number of footer rows"),
        ("Dataset File", "Character encoding"),
        ("Dataset File", "Hash value for checksum"),
        ("Variables", "Google Cloud Platform BigQuery Table Name"),
        ("Variables", "Variable name"),
        ("Variables", "Variable Data Type"),
        ("Variables", "GCP Data Type"),
        ("Variables", "Variable length/precision"),
        ("Variables", "Variable format"),
        ("Variables", "Nullability"),
    ],
}
