V1_TEMPLATE = [
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Name",
        "ref_cell": "B2",
        "value_col": "F",
        "row_start": 2,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Description",
        "ref_cell": "B3",
        "value_col": "F",
        "row_start": 3,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Abstract",
        "ref_cell": "B4",
        "value_col": "F",
        "row_start": 4,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Acronym",
        "ref_cell": "B5",
        "value_col": "F",
        "row_start": 5,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Significant Changes",
        "ref_cell": "B6",
        "value_col": "F",
        "row_start": 6,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Sampling-Data Collection",
        "ref_cell": "B7",
        "value_col": "F",
        "row_start": 7,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Creator",
        "ref_cell": "B8",
        "value_col": "F",
        "row_start": 8,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Contributor(s)",
        "ref_cell": "B9",
        "value_col": "F",
        "row_start": 9,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does this Dataset Resource contain data from multiple sources?",
        "ref_cell": "B10",
        "value_col": "F",
        "row_start": 10,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Details of multiple datasets",
        "ref_cell": "B11",
        "value_col": "F",
        "row_start": 11,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Supplier/Provider (owner name and contact information)",
        "ref_cell": "B12",
        "value_col": "F",
        "row_start": 12,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Name of representative completing the sensitivity assessment if different from the above",
        "ref_cell": "B13",
        "value_col": "F",
        "row_start": 13,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "ONS Operational Contact Name",
        "ref_cell": "B14",
        "value_col": "F",
        "row_start": 14,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Purpose of this Dataset Resource",
        "ref_cell": "B15",
        "value_col": "F",
        "row_start": 15,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Sensitivity tool reference number (ServiceNow)",
        "ref_cell": "B16",
        "value_col": "F",
        "row_start": 16,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Sensitivity tool URL",
        "ref_cell": "B17",
        "value_col": "F",
        "row_start": 17,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Search keywords",
        "ref_cell": "B18",
        "value_col": "F",
        "row_start": 18,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Domain",
        "ref_cell": "B19",
        "value_col": "F",
        "row_start": 19,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Theme",
        "ref_cell": "B20",
        "value_col": "F",
        "row_start": 20,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "IDS Business Catalogue Identifier",
        "ref_cell": "B21",
        "value_col": "F",
        "row_start": 21,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Other Unique Identifier(s) for Dataset Resource",
        "ref_cell": "B22",
        "value_col": "F",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Temporal Coverage",
        "ref_cell": "B23",
        "value_col": "F",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Frequency ",
        "ref_cell": "B24",
        "value_col": "F",
        "row_start": 24,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Geographic Coverage",
        "ref_cell": "B25",
        "value_col": "F",
        "row_start": 25,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Geographic Level",
        "ref_cell": "B26",
        "value_col": "F",
        "row_start": 26,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Version",
        "ref_cell": "B27",
        "value_col": "F",
        "row_start": 27,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Version Name or Number",
        "ref_cell": "B28",
        "value_col": "F",
        "row_start": 28,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Version Description",
        "ref_cell": "B29",
        "value_col": "F",
        "row_start": 29,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource Metadata version number",
        "ref_cell": "B30",
        "value_col": "F",
        "row_start": 30,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Controller",
        "ref_cell": "B31",
        "value_col": "F",
        "row_start": 31,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Processor",
        "ref_cell": "B32",
        "value_col": "F",
        "row_start": 32,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Legal Gateway",
        "ref_cell": "B33",
        "value_col": "F",
        "row_start": 33,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Other Legal Gateway",
        "ref_cell": "B34",
        "value_col": "F",
        "row_start": 34,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Licensing status",
        "ref_cell": "B35",
        "value_col": "F",
        "row_start": 35,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Sensitivity status for Dataset Resource",
        "ref_cell": "B36",
        "value_col": "F",
        "row_start": 36,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Deal reference (link to Annex)",
        "ref_cell": "B37",
        "value_col": "F",
        "row_start": 37,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Access Method",
        "ref_cell": "B38",
        "value_col": "F",
        "row_start": 38,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Mode of delivery",
        "ref_cell": "B39",
        "value_col": "F",
        "row_start": 39,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Acquisition Date",
        "ref_cell": "B40",
        "value_col": "F",
        "row_start": 40,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Acquisition State",
        "ref_cell": "B41",
        "value_col": "F",
        "row_start": 41,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Date of completion",
        "ref_cell": "B42",
        "value_col": "F",
        "row_start": 42,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Availability Date",
        "ref_cell": "B43",
        "value_col": "F",
        "row_start": 43,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Availability status",
        "ref_cell": "B44",
        "value_col": "F",
        "row_start": 44,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Google Cloud Platform: Project name",
        "ref_cell": "B45",
        "value_col": "F",
        "row_start": 45,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Google Cloud Platform: Dataset name",
        "ref_cell": "B46",
        "value_col": "F",
        "row_start": 46,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Complete Dataset?",
        "ref_cell": "B47",
        "value_col": "F",
        "row_start": 47,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Completeness of dataset",
        "ref_cell": "B48",
        "value_col": "F",
        "row_start": 48,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Placeholder for Sensitivity Assessment scoring (Table of seven categories with drop-downs, plus a total and boxes for revised scoring and reasons). ",
        "ref_cell": "B49",
        "value_col": "F",
        "row_start": 49,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Provider statement for retention, removal or deletion",
        "ref_cell": "B50",
        "value_col": "F",
        "row_start": 50,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Removal Date",
        "ref_cell": "B51",
        "value_col": "F",
        "row_start": 51,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Removal Comments",
        "ref_cell": "B52",
        "value_col": "F",
        "row_start": 52,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Release details",
        "ref_cell": "B53",
        "value_col": "F",
        "row_start": 53,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Protection Impact Assessment",
        "ref_cell": "B54",
        "value_col": "F",
        "row_start": 54,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Retention Date",
        "ref_cell": "B55",
        "value_col": "F",
        "row_start": 55,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Should special care be applied to any of the variables?",
        "ref_cell": "B56",
        "value_col": "F",
        "row_start": 56,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Are there any data provider restrictions (e.g. data use, data delivery)?",
        "ref_cell": "B57",
        "value_col": "F",
        "row_start": 57,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Are there any disclosure issues associated with the data? ",
        "ref_cell": "B58",
        "value_col": "F",
        "row_start": 58,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Cost of this data",
        "ref_cell": "B59",
        "value_col": "F",
        "row_start": 59,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Is this data restricted to certain types or classes of users only?",
        "ref_cell": "B60",
        "value_col": "F",
        "row_start": 60,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Public domain data",
        "ref_cell": "B61",
        "value_col": "F",
        "row_start": 61,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Is this a new IDS ingest, or a refresh of existing data?",
        "ref_cell": "B62",
        "value_col": "F",
        "row_start": 62,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Project name (if applicable)",
        "ref_cell": "B63",
        "value_col": "F",
        "row_start": 63,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Is this project for ONS analysts only?",
        "ref_cell": "B64",
        "value_col": "F",
        "row_start": 64,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "What are the linkage requirements for the data within the project scope?",
        "ref_cell": "B65",
        "value_col": "F",
        "row_start": 65,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does the project have requirements to produce and export outputs based on the data? ",
        "ref_cell": "B66",
        "value_col": "F",
        "row_start": 66,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does the data relate to individuals, businesses or other entities (e.g. properties, digital objects, etc.)?",
        "ref_cell": "B67",
        "value_col": "F",
        "row_start": 67,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does each record represent a unique entity or a group of entities aggregated to a particular level?",
        "ref_cell": "B68",
        "value_col": "F",
        "row_start": 68,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does the Dataset Resource contain personal data?",
        "ref_cell": "B69",
        "value_col": "F",
        "row_start": 69,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does the Dataset Resource contain Basic Personal Identifiers?",
        "ref_cell": "B70",
        "value_col": "F",
        "row_start": 70,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does the Dataset Resource contain Identification Data?",
        "ref_cell": "B71",
        "value_col": "F",
        "row_start": 71,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does the Dataset Resource contain Economic and financial data?",
        "ref_cell": "B72",
        "value_col": "F",
        "row_start": 72,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does the Dataset Resource contain Official Documentation?",
        "ref_cell": "B73",
        "value_col": "F",
        "row_start": 73,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Does the Dataset Resource contain Location Data?",
        "ref_cell": "B74",
        "value_col": "F",
        "row_start": 74,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "What personal or business identifiers are present in the data? (e.g., name, address, UPRN, DoB, NINo, etc.)",
        "ref_cell": "B75",
        "value_col": "F",
        "row_start": 75,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "What other record identifiers are present (e.g. ONS ID, DOI, etc.)",
        "ref_cell": "B76",
        "value_col": "F",
        "row_start": 76,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "How has deidentification been achieved",
        "ref_cell": "B77",
        "value_col": "F",
        "row_start": 77,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Are there any special category attributes in the data? (e.g., ethnicity, health, trade union membership, etc.)",
        "ref_cell": "B78",
        "value_col": "F",
        "row_start": 78,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Purpose of processing",
        "ref_cell": "B79",
        "value_col": "F",
        "row_start": 79,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Public",
        "ref_cell": "B80",
        "value_col": "F",
        "row_start": 80,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Survey Respondents",
        "ref_cell": "B81",
        "value_col": "F",
        "row_start": 81,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Users",
        "ref_cell": "B82",
        "value_col": "F",
        "row_start": 82,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Employees",
        "ref_cell": "B83",
        "value_col": "F",
        "row_start": 83,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Subscribers",
        "ref_cell": "B84",
        "value_col": "F",
        "row_start": 84,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Students",
        "ref_cell": "B85",
        "value_col": "F",
        "row_start": 85,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Customers or Prospective Customers",
        "ref_cell": "B86",
        "value_col": "F",
        "row_start": 86,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Patients",
        "ref_cell": "B87",
        "value_col": "F",
        "row_start": 87,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Children",
        "ref_cell": "B88",
        "value_col": "F",
        "row_start": 88,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data Subjects - Vulnerable Adults",
        "ref_cell": "B89",
        "value_col": "F",
        "row_start": 89,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Additional Information (Data Subjects)",
        "ref_cell": "B90",
        "value_col": "F",
        "row_start": 90,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Are there any commercially sensitive attributes in the data?",
        "ref_cell": "B91",
        "value_col": "F",
        "row_start": 91,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Is the data currently in another ONS platform?",
        "ref_cell": "B92",
        "value_col": "F",
        "row_start": 92,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Data owner approval status",
        "ref_cell": "B93",
        "value_col": "F",
        "row_start": 93,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Last Review Date",
        "ref_cell": "B94",
        "value_col": "F",
        "row_start": 94,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Approval Status",
        "ref_cell": "B95",
        "value_col": "F",
        "row_start": 95,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Approval Date",
        "ref_cell": "B96",
        "value_col": "F",
        "row_start": 96,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Names and roles of key stakeholders at the Data Provider for this Dataset Resource",
        "ref_cell": "B97",
        "value_col": "F",
        "row_start": 97,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Dataset Resource type",
        "ref_cell": "B98",
        "value_col": "F",
        "row_start": 98,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Provenance",
        "ref_cell": "B99",
        "value_col": "F",
        "row_start": 99,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Documentation",
        "ref_cell": "B100",
        "value_col": "F",
        "row_start": 100,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Number of Dataset Series",
        "ref_cell": "B101",
        "value_col": "F",
        "row_start": 101,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Number of structural data files",
        "ref_cell": "B102",
        "value_col": "F",
        "row_start": 102,
        "mandatory": True,
    },
    {
        "tab": "Dataset Resource",
        "name": "Number of non-structural/reference files ",
        "ref_cell": "B103",
        "value_col": "F",
        "row_start": 103,
        "mandatory": False,
    },
    {
        "tab": "Dataset Resource",
        "name": "Number of code list files",
        "ref_cell": "B104",
        "value_col": "F",
        "row_start": 104,
        "mandatory": True,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Resource",
        "ref_cell": "B2",
        "value_col": "B",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Type",
        "ref_cell": "C2",
        "value_col": "C",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Name",
        "ref_cell": "D2",
        "value_col": "D",
        "row_start": 8,
        "mandatory": True,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Description",
        "ref_cell": "E2",
        "value_col": "E",
        "row_start": 8,
        "mandatory": True,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Creator",
        "ref_cell": "F2",
        "value_col": "F",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Reference Period",
        "ref_cell": "G2",
        "value_col": "G",
        "row_start": 8,
        "mandatory": True,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Geographic Coverage",
        "ref_cell": "H2",
        "value_col": "H",
        "row_start": 8,
        "mandatory": True,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Frequency",
        "ref_cell": "I2",
        "value_col": "I",
        "row_start": 8,
        "mandatory": True,
    },
    {
        "tab": "Dataset Series",
        "name": "Expected date of first delivery",
        "ref_cell": "J2",
        "value_col": "J",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Expected date(s) for future deliveries",
        "ref_cell": "K2",
        "value_col": "K",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Metadata version number (if different from number for Dataset Resource)",
        "ref_cell": "L2",
        "value_col": "L",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Resource Wave number/time period covered (Survey only)",
        "ref_cell": "M2",
        "value_col": "M",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Manifest File",
        "ref_cell": "N2",
        "value_col": "N",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Links to online documentation and other useful materials",
        "ref_cell": "O2",
        "value_col": "O",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Sensitivity status for Dataset Series (if different from that for Dataset Resource)",
        "ref_cell": "P2",
        "value_col": "P",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Security classification of Dataset Series",
        "ref_cell": "Q2",
        "value_col": "Q",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Usage Restrictions status",
        "ref_cell": "R2",
        "value_col": "R",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Usage Restrictions details",
        "ref_cell": "S2",
        "value_col": "S",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Disclosure Restriction status",
        "ref_cell": "T2",
        "value_col": "T",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Dataset Series Disclosure Restriction details",
        "ref_cell": "U2",
        "value_col": "U",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset Series",
        "name": "Data Deal reference (link to Annex)",
        "ref_cell": "V2",
        "value_col": "V",
        "row_start": 8,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Dataset Series",
        "ref_cell": "B1",
        "value_col": "B",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "File path and name",
        "ref_cell": "C1",
        "value_col": "C",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "File version number",
        "ref_cell": "D1",
        "value_col": "D",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "File creation date",
        "ref_cell": "E1",
        "value_col": "E",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "File receipt date",
        "ref_cell": "F1",
        "value_col": "F",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "File format",
        "ref_cell": "G1",
        "value_col": "G",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "String identifier",
        "ref_cell": "H1",
        "value_col": "H",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "File description",
        "ref_cell": "I1",
        "value_col": "I",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "Earliest date",
        "ref_cell": "J1",
        "value_col": "J",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Latest date",
        "ref_cell": "K1",
        "value_col": "K",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Reference period",
        "ref_cell": "L1",
        "value_col": "L",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "File size",
        "ref_cell": "M1",
        "value_col": "M",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "File size unit",
        "ref_cell": "N1",
        "value_col": "N",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "Has structure",
        "ref_cell": "O1",
        "value_col": "O",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Is documentation",
        "ref_cell": "P1",
        "value_col": "P",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Documentation type",
        "ref_cell": "Q1",
        "value_col": "Q",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Is code list",
        "ref_cell": "R1",
        "value_col": "R",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "Number of variables",
        "ref_cell": "S1",
        "value_col": "S",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Number of records",
        "ref_cell": "T1",
        "value_col": "T",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "Is this file one of a sequence to be appended back together?",
        "ref_cell": "U1",
        "value_col": "U",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "Number of header rows",
        "ref_cell": "V1",
        "value_col": "V",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "Number of footer rows",
        "ref_cell": "W1",
        "value_col": "W",
        "row_start": 23,
        "mandatory": True,
    },
    {
        "tab": "Dataset File",
        "name": "Does this file contain multiple heterogeneous sets of data?",
        "ref_cell": "X1",
        "value_col": "X",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "File with multiple heterogeneous sets of data - details",
        "ref_cell": "Y1",
        "value_col": "Y",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Is compressed?",
        "ref_cell": "Z1",
        "value_col": "Z",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Compression type",
        "ref_cell": "AA1",
        "value_col": "AA",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Character encoding",
        "ref_cell": "AB1",
        "value_col": "AB",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Checksum method used",
        "ref_cell": "AC1",
        "value_col": "AC",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Hash value for checksum",
        "ref_cell": "AD1",
        "value_col": "AD",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Google Cloud Platform: Table Name",
        "ref_cell": "AE1",
        "value_col": "AE",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Dataset File",
        "name": "Notes",
        "ref_cell": "AF1",
        "value_col": "AF",
        "row_start": 23,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Dataset Series",
        "ref_cell": "B1",
        "value_col": "B",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "Dataset file name",
        "ref_cell": "C1",
        "value_col": "C",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Variable name",
        "ref_cell": "D1",
        "value_col": "D",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "Variable label",
        "ref_cell": "E1",
        "value_col": "E",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "Variable description",
        "ref_cell": "F1",
        "value_col": "F",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "Position in file",
        "ref_cell": "G1",
        "value_col": "G",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Personally Identifiable Information",
        "ref_cell": "H1",
        "value_col": "H",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "Variable data type",
        "ref_cell": "I1",
        "value_col": "I",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "GCP Data Type",
        "ref_cell": "J1",
        "value_col": "J",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "Variable length/precision",
        "ref_cell": "K1",
        "value_col": "K",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Variable format",
        "ref_cell": "L1",
        "value_col": "L",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Is Primary Key",
        "ref_cell": "M1",
        "value_col": "M",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "Is Foreign Key",
        "ref_cell": "N1",
        "value_col": "N",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "Foreign Key file name",
        "ref_cell": "O1",
        "value_col": "O",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Foreign Key variable name",
        "ref_cell": "P1",
        "value_col": "P",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Nullability",
        "ref_cell": "Q1",
        "value_col": "Q",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "NULL values denoted by",
        "ref_cell": "R1",
        "value_col": "R",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Variable constraints",
        "ref_cell": "S1",
        "value_col": "S",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Applicable business rules",
        "ref_cell": "T1",
        "value_col": "T",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Is this a code?",
        "ref_cell": "U1",
        "value_col": "U",
        "row_start": 22,
        "mandatory": True,
    },
    {
        "tab": "Variables",
        "name": "Is this a standard, calculated, or derived variable?",
        "ref_cell": "V1",
        "value_col": "V",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Is the derived variable status disclosable?",
        "ref_cell": "W1",
        "value_col": "W",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "If a calculated or derived variable, how is it calculated/derived?",
        "ref_cell": "X1",
        "value_col": "X",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "If a calculated or derived variable, is the algorithm/process disclosable?",
        "ref_cell": "Y1",
        "value_col": "Y",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Variables",
        "name": "Notes",
        "ref_cell": "Z1",
        "value_col": "Z",
        "row_start": 22,
        "mandatory": False,
    },
    {
        "tab": "Codes and Values",
        "name": "Dataset Series",
        "ref_cell": "B1",
        "value_col": "B",
        "row_start": 17,
        "mandatory": True,
    },
    {
        "tab": "Codes and Values",
        "name": "Dataset file name",
        "ref_cell": "C1",
        "value_col": "C",
        "row_start": 17,
        "mandatory": False,
    },
    {
        "tab": "Codes and Values",
        "name": "Variable name",
        "ref_cell": "D1",
        "value_col": "D",
        "row_start": 17,
        "mandatory": True,
    },
    {
        "tab": "Codes and Values",
        "name": "Key",
        "ref_cell": "E1",
        "value_col": "E",
        "row_start": 17,
        "mandatory": True,
    },
    {
        "tab": "Codes and Values",
        "name": "Value",
        "ref_cell": "F1",
        "value_col": "F",
        "row_start": 17,
        "mandatory": True,
    },
    {
        "tab": "Codes and Values",
        "name": "Notes",
        "ref_cell": "G1",
        "value_col": "G",
        "row_start": 17,
        "mandatory": False,
    },
]
