"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emissary_client_sdk.types import BaseModel
from emissary_client_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class RetrieveBaseModelByNameRequestTypedDict(TypedDict):
    base_model_name: str
    r"""The name of the base model to retrieve"""


class RetrieveBaseModelByNameRequest(BaseModel):
    base_model_name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The name of the base model to retrieve"""
