# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.activity_update_request_data import ActivityUpdateRequestData
from openapi_server import util


class ActivityUpdateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: ActivityUpdateRequestData=None):
        """ActivityUpdateRequest - a model defined in OpenAPI

        :param data: The data of this ActivityUpdateRequest.
        """
        self.openapi_types = {
            'data': ActivityUpdateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ActivityUpdateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Activity_update_request of this ActivityUpdateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ActivityUpdateRequest.


        :return: The data of this ActivityUpdateRequest.
        :rtype: ActivityUpdateRequestData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ActivityUpdateRequest.


        :param data: The data of this ActivityUpdateRequest.
        :type data: ActivityUpdateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
