# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.conversation_message_create_request_data import ConversationMessageCreateRequestData
from openapi_server import util


class ConversationMessageCreateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: ConversationMessageCreateRequestData=None):
        """ConversationMessageCreateRequest - a model defined in OpenAPI

        :param data: The data of this ConversationMessageCreateRequest.
        """
        self.openapi_types = {
            'data': ConversationMessageCreateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ConversationMessageCreateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ConversationMessage_create_request of this ConversationMessageCreateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ConversationMessageCreateRequest.


        :return: The data of this ConversationMessageCreateRequest.
        :rtype: ConversationMessageCreateRequestData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ConversationMessageCreateRequest.


        :param data: The data of this ConversationMessageCreateRequest.
        :type data: ConversationMessageCreateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
