# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.custom_field_set import CustomFieldSet
from openapi_server import util


class CustomFieldSetShow(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: CustomFieldSet=None):
        """CustomFieldSetShow - a model defined in OpenAPI

        :param data: The data of this CustomFieldSetShow.
        """
        self.openapi_types = {
            'data': CustomFieldSet
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CustomFieldSetShow':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CustomFieldSet_Show of this CustomFieldSetShow.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CustomFieldSetShow.


        :return: The data of this CustomFieldSetShow.
        :rtype: CustomFieldSet
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CustomFieldSetShow.


        :param data: The data of this CustomFieldSetShow.
        :type data: CustomFieldSet
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
