# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.report import Report
from openapi_server import util


class ReportShow(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: Report=None):
        """ReportShow - a model defined in OpenAPI

        :param data: The data of this ReportShow.
        """
        self.openapi_types = {
            'data': Report
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ReportShow':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Report_Show of this ReportShow.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ReportShow.


        :return: The data of this ReportShow.
        :rtype: Report
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ReportShow.


        :param data: The data of this ReportShow.
        :type data: Report
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
