# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.text_snippet_update_request_data import TextSnippetUpdateRequestData
from openapi_server import util


class TextSnippetUpdateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: TextSnippetUpdateRequestData=None):
        """TextSnippetUpdateRequest - a model defined in OpenAPI

        :param data: The data of this TextSnippetUpdateRequest.
        """
        self.openapi_types = {
            'data': TextSnippetUpdateRequestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TextSnippetUpdateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TextSnippet_update_request of this TextSnippetUpdateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this TextSnippetUpdateRequest.


        :return: The data of this TextSnippetUpdateRequest.
        :rtype: TextSnippetUpdateRequestData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this TextSnippetUpdateRequest.


        :param data: The data of this TextSnippetUpdateRequest.
        :type data: TextSnippetUpdateRequestData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
